# Site
repository: KatarzynaSzmydki/KatarzynaSzmydki.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Katarzyna Szmydki
title: BI Developer | Data Analyst

# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username:  KatarzynaSzmydki
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: katarzyna-szmydki-aa0b79b5


# Additional icon links

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Dedicated and friendly BI developer/Data analyst with 6+ years experience. Currently, in a customer-facing role providing BI solutions to clients from various domains. 
  Having professional experience in FMCG and technology companies I gained most important skill - ability to translate business requirements into BI solutions that make clients' day-to-day work easier. 
  Keen to utilise my skills to create practical solutions with a heavy emphasis on great user experience.

  I'm most skilled in: 
  - Extracting, cleaning and preparing data (<mark>SQL</mark>, <mark>Python</mark>, <mark>PySpark</mark>),
  - Building reporting (<mark>Power BI</mark>) based on both on-prem data infrastructure and public cloud (*AWS*, *Azure*), 
  - Consolidating and explaining complex issues to business in easily digestable form. 
  
  Next in my technology bucket list:
  - Databricks
  - Snowflake
  
  
  Certificates
  - <a href="google.com">Links</a>
  - Images ![alt text](/images/landscape-trees.jpg "Trees")


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: PwC IT Services
        sub_title: Senior BI Developer
        caption: April 2023 - Present
        description: | # this will include new lines to allow paragraphs
          Developing reports (*Power BI*) and cloud-based (*Azure*) data solutions for clients from various domains.

      - layout: left
        title: StepStone Services
        sub_title: Data Analyst
        caption: July 2022 - March 2023
        description: | # this will include new lines to allow paragraphs
          Creating reports (*Power BI*), conducting exploratory and explanatory analyses (*SQL/Python/PySpark*). Extracting and transforming data from diverse sources (*Redshift DW/S3/Apache Hive/API*). Daily cooperation with developers, PO, business.

      - layout: left
        title: Philip Morris International
        sub_title: BI/IT Developer
        caption: Mar 2017 - July 2022
        description: | # this will include new lines to allow paragraphs
          Service management, supporting and maintaining Business Intelligence tools, business analysis, cloud technologies.     


  - title: Latest Power BI showcases
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Store performance report
        description: |
          Report analysing store sales performance across different countries/cities and store formats (dummy data).
        link: https://app.powerbi.com/view?r=eyJrIjoiNzMwOTBkMDctNTA5ZC00OTAwLWIyNTQtZGIyZTNmMzdhNTc4IiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
        link_text: Go to the report

      - layout: left
        title: Product sales report
        description: |
          Report analysing sales performance for an alcohol company. Includes performance metrics tracked over time and across categories and brands (dummy data).
        link: https://app.powerbi.com/view?r=eyJrIjoiMmFkYzdjODQtYmY1Ny00MjQzLThiM2ItMWNlODE5YWVjNzM0IiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
        link_text: Go to the report
#
#      - layout: left
#        title: Airbnb short-term rental housing report
#        description: |
#          Based on publicly available Beijing Airbnb dataset published on April 17, 2019. Report presents basic statistics and findings from used dataset (PBI).
#        link: https://app.powerbi.com/view?r=eyJrIjoiOWFiODc5NDYtMDAxMS00OGU5LWJjZmYtOTZiYTlkMzA5ZTQyIiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
#        link_text: Go to the report


#  - title: Kaggle projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: Sales dashboard
#        link: https://app.powerbi.com/view?r=eyJrIjoiMjkyNDQ5MjgtNzU1OS00NDMyLWIyY2ItMjA4NTllOTY0NmNjIiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9&pageName=ReportSection
#        link_text: Go to the app



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
