# Site
repository: KatarzynaSzmydki/KatarzynaSzmydki.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Katarzyna Szmydki
title: BI Developer | Data Analyst

# Dark Mode (true/false/never)
darkmode: false

# Social links

github_username:  KatarzynaSzmydki
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: katarzyna-szmydki-aa0b79b5


# Additional icon links

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Dedicated and friendly BI developer/Data analyst with 6+ years experience. Currently, in a customer-facing role providing BI solutions to clients from various domains. 
  Having professional experience in FMCG and technology companies I gained most important skill - ability to translate business requirements into BI solutions that make clients' day-to-day work easier. 
  Keen to utilise my skills to create practical solutions with a heavy emphasis on great user experience.

  I'm most skilled in: 
  - Extracting, cleaning and preparing data with use of <mark>SQL</mark>, <mark>Python</mark>, <mark>PySpark</mark>,
  - Building reporting in <mark>Power BI</mark> based on both on-prem data infrastructure and public cloud (*MS Azure*, *AWS*), 
  - Consolidating and explaining complex issues to business in easily digestable form. 
  
  Next in my technology bucket list:
  - MS Fabric
  - Snowflake




  ![alt text](/images/cv.png) View my current CV under following <a href="/images/Katarzyna_Szmydki_CV.pdf">link</a> .
  

#  <a href="https://www.credly.com/badges/f3371305-d7a9-4b79-a84a-33a03e9dc5bb/public_url"> </a>
#  ![alt text](/images/PBI_badge.png width="200" height="121" alt="Microsoft Certified: Power BI Data Analyst Associate")
#  <a href="https://credentials.databricks.com/5e313a22-3a5f-4ed7-9823-0636370ca3fd"> </a>
#  ![alt text](/images/lakehouse-fundamentals.png width="200" height="121" alt="Databricks Lakehouse Fundamentals")




content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: PwC IT Services
        sub_title: Senior BI Developer
        caption: April 2023 - Present
        description: | # this will include new lines to allow paragraphs
          Developing reports (*Power BI*) and cloud-based (*MS Azure*) data solutions for clients from various domains.

      - layout: left
        title: StepStone Services
        sub_title: Data Analyst
        caption: July 2022 - March 2023
        description: | 
          Creating reports (*Power BI*), conducting exploratory and explanatory analyses (*SQL/Python/PySpark*). Extracting and transforming data from diverse sources (*Redshift DW/S3/Apache Hive/API*). Daily cooperation with developers, PO, business. 

      - layout: left
        title: Philip Morris International
        sub_title: BI/IT Developer
        caption: Mar 2017 - July 2022
        description: | 
          Service management, supporting and maintaining Business Intelligence tools, business analysis, cloud technologies.     


  - title: Latest projects
    layout: list
    content:
      - layout: left
        title: Loan Request Verification Tool
        description: |
          <mark>New!</mark> 
          
          Project implements scoring model within Flask application. User inputs basic financial information regarding loan request in a Flask form. Request is scored using pretrained ML model on saving to database (Azure SQL database) and flag informing whether user will or will not be granted the loan is assigned to the record.
          Application enables updating loan data or deleting records altogether. Each edit action triggers loan request scoring recalculation. 
          
          Summary statistics for processed requests are presented within PBI report embedded in the application. 
          
          Key project features: Python Flask application, Azure SQL Database, ML model, PBI report
          
          Link to working solution: https://loanapplicationverification.azurewebsites.net/
        link: https://github.com/KatarzynaSzmydki/Loan_Request_Verification/tree/master
        link_text: Go to Project GitHub repository

      - layout: left
        title: Budget Management Tool
        description: |
          Tool for managing monthly expenses and budgets. It uses Power Apps application embedded within Power BI report. Users can report expenses, define budgets and analyse full expense history. 
          
          Key report features: expense histogram with dynamic bin sizes, bookmark tabs
        link: https://app.powerbi.com/view?r=eyJrIjoiMzM5YWViOWMtMzNhOS00ZGU3LWE0NmUtZjZjMTY3YzM4ODM1IiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
        link_text: Go to the report

      - layout: left
        title: Spotify Tracks Analysis report
        description: |
          Report analyses Spotify tracks data. It uses Azure Databrics for data transformation and analysis and Azure Data Lake Storage Gen2 for storing raw and processed data. PBI report connects to relevant tables in Azure Synapse Analytics. 
          
          Key report features: field parameters, new KPI cards, SVG charts, dynamic formatting, page and bookmark navigation buttons
        link: https://app.powerbi.com/view?r=eyJrIjoiZTQ3MWEyYmEtZmYxNi00MTQ5LTlkOTktNmFhZGU4MmY1YjZjIiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
        link_text: Go to the report

      - layout: left
        title: Store performance report
        description: |
          Report analysing store sales performance across different countries/cities and store formats (dummy data).
        link: https://app.powerbi.com/view?r=eyJrIjoiNzMwOTBkMDctNTA5ZC00OTAwLWIyNTQtZGIyZTNmMzdhNTc4IiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
        link_text: Go to the report

      - layout: left
        title: Product sales report
        description: |
          Report analysing sales performance for an alcohol company. Includes performance metrics tracked over time and across categories and brands (dummy data).
        link: https://app.powerbi.com/view?r=eyJrIjoiMmFkYzdjODQtYmY1Ny00MjQzLThiM2ItMWNlODE5YWVjNzM0IiwidCI6IjI5NDYwNjgyLTUwNmQtNDcxNy05NmE3LTUxNDg1OGRjMjIyZCIsImMiOjh9
        link_text: Go to the report




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
google_verify: sclWa7vBIzhjqtoysEq5PWoI5wW8EIN4_YN881LsMYM
google-site-verification: sclWa7vBIzhjqtoysEq5PWoI5wW8EIN4_YN881LsMYM
